### ISSUE TITLE
Upstream updates for 2021-03-08

### ISSUE THREAD

**Issue by jackpot51** [pop-os/systemd#11]
Stage updates:
- [x] focal: https://launchpad.net/ubuntu/+source/systemd/245.4-4ubuntu3.5
- [x] groovy: https://launchpad.net/ubuntu/+source/systemd/246.6-1ubuntu1.2

Test updates:
- [x] focal: https://github.com/pop-os/systemd/commit/d10e396834fdda5d1ed6276754ab5b24634b714e
- [x] groovy: https://github.com/pop-os/systemd/commit/d80d6a1cf0366d5e787c49e01cb1f544a2959566

**Comment by jacobgkau** [comment]
Looking fine on Groovy:
- [X] Confirmed all Pop!_OS patches are still present
- [X] Shutdown/reboot work
- [X] Able to use the boot menu & updating initramfs works normally (systemd-boot)
- [X] Service management works normally
- [X] Virtual machine works
- [X] Suspend/resume works (in NVIDIA mode and Integrated mode)
- [X] DNS resolution works w/ automatic and custom settings (systemd-resolved)
- [X] NTP works (systemd-timesyncd)
- [X] Able to view logs with journalctl (systemd-journald)

**Comment by jacobgkau** [comment]
Not seeing any problems on Focal either:
- [X] Confirmed all Pop!_OS patches are still present
- [X] Shutdown/reboot work
- [X] Able to use the boot menu & updating initramfs works normally (systemd-boot)
- [X] Service management works normally
- [X] Virtual machine works
- [X] Suspend/resume works (in NVIDIA mode and Integrated mode)
- [X] DNS resolution works w/ automatic and custom settings (systemd-resolved)
- [X] NTP works (systemd-timesyncd)
- [X] Able to view logs with journalctl (systemd-journald)
