### ISSUE TITLE
Update to v248 or later for sleep management improvement (to fix suspend-then-hibernate with nvidia)

### ISSUE THREAD

**Issue by cstrahan** [pop-os/systemd#15]
**Is your feature request related to a problem? Please describe.**

As described in https://github.com/systemd/systemd/issues/18092, prior to v248 (in the PR https://github.com/systemd/systemd/pull/18110) there was no way in systemd to hook into the separate steps involved in suspend-then-hibernate. As a result, nvidia has no way to properly resume (it currently just locks the screen up, requiring a reboot) from suspend-then-hibernate. Having suspend-then-hibernate working is important to me because I like to close my lid when I'm going to step away from my computer for some indeterminate amount of time; if I'm back at my laptop within 15 minutes, I'd prefer to just wake from suspend and get back to work, instead of having to boot back up, decrypt file system, resume from hibernation, and then log back in. Otherwise, I really want my laptop to hibernate, because my laptop (gaze16) battery drains over night.

**Describe the solution you'd like**
Updating to at least v248 (or for now just cherry-picking https://github.com/systemd/systemd/pull/18110) should allow for for amending the nvidia sleep script (`/usr/lib/systemd/system-sleep/nvidia`) so that sleep-then-hibernate works.

**Describe alternatives you've considered**
No good alternatives that I can think of.

**Comment by jacobgkau** [comment]
It looks like 21.10 already has systemd 248. Can you confirm your issue is not occurring in the 21.10 beta? https://github.com/pop-os/beta

**Comment by cstrahan** [comment]
> It looks like 21.10 already has systemd 248. Can you confirm your issue is not occurring in the 21.10 beta? [pop-os/beta](https://github.com/pop-os/beta)

With the systemd used in 21.10, I can confirm that I got `suspend-then-hibernate` working.

Tweaked code from https://forums.developer.nvidia.com/t/systemds-suspend-then-hibernate-not-working-in-nvidia-optimus-laptop/213690 and saved it to `/usr/lib/systemd/system-sleep/nvidia`:

```bash
#!/bin/sh

case "$1" in
    pre)
        case "$SYSTEMD_SLEEP_ACTION" in
            suspend|hibernate)
                /usr/bin/nvidia-sleep.sh "$SYSTEMD_SLEEP_ACTION"
                ;;
            suspend-after-failed-hibernate)
                /usr/bin/nvidia-sleep.sh "suspend"
                ;;
        esac
        ;;
    post)
        /usr/bin/nvidia-sleep.sh "resume"
        sleep 4 # give some time between post-resume and pre-hibernate
        ;;
esac
```

Also, disable the nvidia sleep units:

```
sudo systemctl disable nvidia-{hibernate,suspend,resume}.service
sudo systemctl mask nvidia-{hibernate,suspend,resume}.service
```

Now `suspend-then-hibernate` works.

---

Some other notes:

Without the `sleep`, the writes to `/proc/driver/nvidia/suspend` upon post-resume-from-suspend and pre-hibernate occur too rapidly for the nvidia driver to properly handle -- the system will suspend, wake and then hibernate as expected, but it will then hang after you try to resume from hibernation. FWIW, while I was debugging that hang (before I figured out the work around), I put this at the top of the script `echo "$(date)  $1  $2  $SYSTEMD_SLEEP_ACTION" >> /var/log/my-sleep-log
` and I saw this in my log file:

```
Sun Jun 12 08:58:41 PM CDT 2022  pre  suspend-then-hibernate  suspend
Sun Jun 12 08:58:53 PM CDT 2022  post  suspend-then-hibernate  suspend
Sun Jun 12 08:58:54 PM CDT 2022  pre  suspend-then-hibernate  hibernate
```

and that's all. After putting in the `sleep`, the log file looks like after a full suspend-resume-hibernate-resume cycle:

```
Sun Jun 12 09:28:19 PM CDT 2022  pre  suspend-then-hibernate  suspend
Sun Jun 12 09:28:31 PM CDT 2022  post  suspend-then-hibernate  suspend
Sun Jun 12 09:28:36 PM CDT 2022  pre  suspend-then-hibernate  hibernate
Sun Jun 12 09:29:18 PM CDT 2022  post  suspend-then-hibernate  hibernate
```

For testing, I set `HibernateDelaySec=10` in `/etc/systemd/sleep.conf` and ran `sudo systemctl suspend-then-hibernate`.

**Comment by cstrahan** [comment]
Other links that might be useful to people stumbling on this issue:
- https://download.nvidia.com/XFree86/Linux-x86_64/435.17/README/powermanagement.html
- https://www.freedesktop.org/software/systemd/man/systemd-suspend.service.html

**Comment by postmdk** [comment]
I did this:

1. created a unit in /usr/lib/systemd/system/nvidia-suspend-then-hibernate.service
```
[Unit]
Description=NVIDIA system suspend-then-hibernate actions
Before=systemd-suspend-then-hibernate.service

[Service]
Type=oneshot
ExecStart=/usr/bin/logger -t suspend -s "nvidia-suspend-then-hibernate.service"
ExecStart=/usr/bin/nvidia-sleep.sh "hibernate"

[Install]
WantedBy=systemd-suspend-then-hibernate.service
```
2. edit unit /usr/lib/systemd/system/nvidia-resume.service
```
[Unit]
Description=NVIDIA system resume actions
After=systemd-suspend.service
After=systemd-hibernate.service
After=systemd-suspend-then-hibernate.service

[Service]
Type=oneshot
ExecStart=/usr/bin/logger -t suspend -s "nvidia-resume.service"
ExecStart=/usr/bin/nvidia-sleep.sh "resume"

[Install]
WantedBy=systemd-suspend.service
WantedBy=systemd-hibernate.service
WantedBy=systemd-suspend-then-hibernate.service
```
3. remove file /usr/lib/systemd/system-sleep/nvidia

4.
```
#systemctl daemon-reload
#systemctl disable nvidia-resume.service
#systemctl enable nvidia-suspend.service
#systemctl enable nvidia-hibernate.service
#systemctl enable nvidia-suspend-then-hibernate.service
#systemctl enable nvidia-resume.service
```
for check

 in /etc/systemd/sleep.conf set HibernateDelaySec=3min

warning, do not set the interval to less than 1 minute.

Command: 
``` 
systemctl suspend-then-hibernate
```
it works.

checked on debian 12 end gentoo systemd version 255 nvidia-drivers version 550.67

**Comment by jacobgkau** [comment]
> checked on debian 12 end gentoo systemd version 255 nvidia-drivers version 550.67

While the information is appreciated, this repo is specific to the version of systemd being packaged and shipped in Pop!_OS.

I'm going to go ahead and close this; it was requesting version 248+, and 22.04 LTS is currently on 249.11. Discussion about hibernate and suspend+hibernate in Pop!_OS is fine, but it's outside the scope of this repo.
